"""alter table booking add total_price

Revision ID: 037f4097a245
Revises: e2b8cb00f277
Create Date: 2024-09-28 10:13:50.421307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037f4097a245'
down_revision = 'e2b8cb00f277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
