"""alter the col name of the car_name field in the cars table to name

Revision ID: 2eff7a36d0fd
Revises: dc41fbfca90e
Create Date: 2024-04-26 20:20:32.408221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2eff7a36d0fd'
down_revision = 'dc41fbfca90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.drop_column('car_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
