"""modify pickup_time, and return_time to Time type

Revision ID: 6c9613f5558d
Revises: 838d33b12aaa
Create Date: 2024-09-24 16:56:09.065600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c9613f5558d'
down_revision = '838d33b12aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('pickup_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('return_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('return_time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('pickup_time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
