"""Recreate booking table

Revision ID: e2b8cb00f277
Revises: 6c9613f5558d
Create Date: 2024-09-24 19:33:57.536872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b8cb00f277'
down_revision = '6c9613f5558d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('pickup_time', sa.Time(), nullable=False),
    sa.Column('return_time', sa.Time(), nullable=False),
    sa.Column('pick_up_loc', sa.Integer(), nullable=False),
    sa.Column('drop_off_loc', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['drop_off_loc'], ['location.id'], ),
    sa.ForeignKeyConstraint(['pick_up_loc'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_pickup_time'), ['pickup_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_return_time'), ['return_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_return_time'))
        batch_op.drop_index(batch_op.f('ix_booking_pickup_time'))
        batch_op.drop_index(batch_op.f('ix_booking_created_at'))

    op.drop_table('booking')
    # ### end Alembic commands ###
