"""Added likes relationship between User and Car

Revision ID: f0a16a01cfc2
Revises: 43856ba4c792
Create Date: 2024-09-11 23:05:43.259622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0a16a01cfc2'
down_revision = '43856ba4c792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'car_id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint('cars_ibfk_1', type_='foreignkey')
        batch_op.drop_column('like_users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_users', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('cars_ibfk_1', 'users', ['like_users'], ['id'])

    op.drop_table('likes')
    # ### end Alembic commands ###
