"""creat cars table

Revision ID: f62ab32e0d22
Revises: 7d2fe949e218
Create Date: 2024-04-23 23:58:23.018406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62ab32e0d22'
down_revision = '7d2fe949e218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(length=255), nullable=False),
    sa.Column('displacement', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('door', sa.Integer(), nullable=False),
    sa.Column('car_length', sa.Integer(), nullable=False),
    sa.Column('wheelbase', sa.Integer(), nullable=False),
    sa.Column('power_type', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('available_time', sa.DateTime(), nullable=False),
    sa.Column('last_return_time', sa.DateTime(), nullable=False),
    sa.Column('like_users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['like_users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
